### ISSUE TITLE
merg master to branch

### ISSUE THREAD

**Issue by Feruzteame** [adekimpianna/semantic-layout-collaborative-exercise#14]
guys merge master to branch it create conflict. look the picture the black line is master . it goes down that means it you merge master to branch. we should have merg the branch to master. I think  feruz, yana and miroslav make a mistake.  what do you think?

![Screenshot 2020-06-02 at 18 44 30](https://user-images.githubusercontent.com/59234162/83546536-1c812f00-a501-11ea-8f2f-6c2b4757f3d9.png)

**Comment by harunaltunhr** [comment]
@Feruzteame I think you are wrong, it is not a conflict. They pull master at that stage( and black shows us pulling from master) they merge it in their branch and then they push it again to master. This is another way for merging. This will not create a conflict. Of course we face to conflict and every member should resolve conflict when merging their branch. 

What is your suggestion? How can we merge it without any conflict? Because at the begining, master is empty and then I merged my branch( aside-text), after this every branch will resolve a conflict at merging. If somebody know another way, then we use

**Comment by adekimpianna** [comment]
@Feruzteame if you see carefully, my branch and miroslav pulled/rebased our local master from remote master (the black diagonal line), then we merged our branch back to the remote master. Can you see our line goes back to the master straight line again?

We did exactly like instructions from last week exercise: Git Workflow for two programmers, stage 13, 14, 15. https://github.com/HackYourFutureBelgium/git-workflow-workshop-for-two please read again, if you dont remember.

But, of course, we can also merge our master into the branch, like what you are doing. Now, if we accept your pull request, your branch will be the most updated one (because it contains harun, miroslav and my work), and our master will be one step behind. So what do you suggest?

**Comment by adekimpianna** [comment]
This is the network from another group, group 6. They used last week instructions to solve conflicts and it looked like our network. https://github.com/lisarosaa/lastgroupbio/network
![image](https://user-images.githubusercontent.com/62487749/83563899-1e0c2080-a51c-11ea-81a3-2a9bbf4cb896.png)

**Comment by harunaltunhr** [comment]
@adekimpianna You are wrong. @Feruzteame branch not the most updated, it is wrong. It only has her code. If we merge it, Index.html only has that branch not yours code, not mine, not miroslav's code. Please do not accept pull request.

**Comment by harunaltunhr** [comment]
We need a short meeting to solve, I suggest

**Comment by adekimpianna** [comment]
> 
> 
> @adekimpianna You are wrong. @Feruzteame branch not the most updated, it is wrong. It only has her code. If we merge it, Index.html only has that branch not yours code, not mine, not miroslav's code. Please do not accept pull request.

oh yeah, I just checked it once again. I am sorry @Feruzteame, this time @harunaltunhr is right.

**Comment by Feruzteame** [comment]
When i work in git hub i work in diffrent way. I never merge master to branch. I merge my branches to master. May be can you explain or help me to your system. May be zoom? If it is possible.

**Comment by Feruzteame** [comment]
I am not understand even your comment. May be i lost.

**Comment by harunaltunhr** [comment]
Feruz this is the same. They are also merge their branch to master. But master has some codes so you need to resolve conflict. If possible for you tomorrow 13:00 we will do a short meeting? Is it ok? If not pls write your times so we can arrange a zoom

**Comment by Feruzteame** [comment]
When i start to resolve the conflict i found i alot of text in my branch i thought it is conflict.that's why i delet it.

**Comment by Feruzteame** [comment]
For me at 13:00 it is okay. Really i need your explansion.

**Comment by adekimpianna** [comment]
Guys, Stephane said that he could have a short zoom meeting about solving conflict with us, **tomorrow at 12.00**, if you are available please join. He will give us the link to his zoom later.
  
@Boam1994 @Feruzteame @murvanessa @miroslavveljanoski @harunaltunhr

**Comment by Feruzteame** [comment]
Waw good what about today ?
We had plan to meet at 13

**Comment by adekimpianna** [comment]
@Feruzteame if it is okay with you, the meeting today at 13.00 we can still do it too with @harunaltunhr  
  
This my zoom link https://us04web.zoom.us/j/7365542711?pwd=eWtQc1FWYmxUSTNES0U4MUZraU1wZz09

**Comment by Feruzteame** [comment]
Thank you yana
